// Definisi menu utama: dipakai TitleBar dan pemetaan shortcut global
export const MENUS: Record<string, { label: string; hint?: string; action: string }[]> = {
  File: [
    { label: "Dokumen Baru", hint: "Ctrl+N", action: "new-doc" },
    { label: "Home", hint: "", action: "home" },
    { label: "Buka Gambar", hint: "Ctrl+O", action: "open" },
    { label: "Buka Proyek .avx", hint: "Ctrl+O", action: "open-avx" },
    { label: "Simpan Proyek", hint: "Ctrl+S", action: "save-avx" },
    { label: "Simpan Proyek Sebagai", hint: "Ctrl+Shift+S", action: "save-avx-as" },
    { label: "Export Gambar", hint: "Ctrl+E", action: "export" },
    { label: "Export Cepat PNG", hint: "", action: "export-png" },
    { label: "Tutup Dokumen", hint: "", action: "close-doc" },
  ],
  Edit: [
    { label: "Undo", hint: "Ctrl+Z", action: "undo" },
    { label: "Redo", hint: "Ctrl+Y", action: "redo" },
    { label: "Semua Aksi", hint: "Ctrl+K", action: "palette" },
    { label: "Potong", hint: "Ctrl+X", action: "cut" },
    { label: "Salin", hint: "Ctrl+C", action: "copy" },
    { label: "Tempel", hint: "Ctrl+V", action: "paste" },
    { label: "Hapus Isi", hint: "Delete", action: "clear-fill" },
    { label: "Isi Dengan Warna Foreground", hint: "Alt+Backspace", action: "fill-fg" },
    { label: "Isi Dengan Warna Background", hint: "Ctrl+Backspace", action: "fill-bg" },
    { label: "Isi Dengan Isi Isi (Content-Aware)", hint: "Shift+F5", action: "content-aware" },
    { label: "Transform Bebas", hint: "Ctrl+T", action: "free-transform" },
    { label: "Putar 90 Derajat Kanan", hint: "", action: "rotate-cw" },
    { label: "Putar 90 Derajat Kiri", hint: "", action: "rotate-ccw" },
    { label: "Balik Horizontal", hint: "", action: "flip-h" },
    { label: "Balik Vertikal", hint: "", action: "flip-v" },
    { label: "Atur Ulang Warna", hint: "", action: "reset-color" },
    { label: "Preferensi", hint: "Ctrl+,", action: "prefs" },
  ],
  Image: [
    { label: "Ukuran Gambar", hint: "Ctrl+Alt+I", action: "img-size" },
    { label: "Ukuran Kanvas", hint: "Ctrl+Alt+C", action: "canvas-size" },
    { label: "Trim", hint: "", action: "trim" },
    { label: "Rotasi Kanvas 90 Kanan", hint: "", action: "canvas-cw" },
    { label: "Rotasi Kanvas 90 Kiri", hint: "", action: "canvas-ccw" },
    { label: "Mode Warna 8-bit", hint: "", action: "mode-8" },
    { label: "Mode Warna 16-bit", hint: "", action: "mode-16" },
    { label: "Soft Proof CMYK", hint: "", action: "proof" },
    { label: "Histogram", hint: "", action: "histogram" },
    { label: "Auto Tone", hint: "Ctrl+Shift+L", action: "auto-tone" },
    { label: "Auto Contrast", hint: "Ctrl+Shift+Alt+L", action: "auto-contrast" },
    { label: "Auto Color", hint: "Ctrl+Shift+B", action: "auto-color" },
    { label: "Invert Warna", hint: "Ctrl+I", action: "invert" },
    { label: "Desaturate", hint: "Ctrl+Shift+U", action: "desaturate" },
    { label: "Threshold", hint: "", action: "threshold" },
    { label: "Posterize", hint: "", action: "posterize" },
    { label: "Fit Zoom", hint: "", action: "fit" },
    { label: "Zoom 100%", hint: "", action: "zoom100" },
    { label: "Rulers", hint: "", action: "rulers" },
    { label: "Grid", hint: "'", action: "grid" },
    { label: "Guides", hint: "", action: "guides" },
  ],
  Layer: [
    { label: "Layer Baru", hint: "Ctrl+Shift+N", action: "add-layer" },
    { label: "Duplikat Layer", hint: "Ctrl+J", action: "dup-layer" },
    { label: "Layer via Copy", hint: "Ctrl+J", action: "layer-copy" },
    { label: "Layer via Cut", hint: "Ctrl+Shift+J", action: "layer-cut" },
    { label: "Hapus Layer", hint: "", action: "del-layer" },
    { label: "Layer Group", hint: "Ctrl+G", action: "group" },
    { label: "Naikkan Layer", hint: "Ctrl+]", action: "layer-up" },
    { label: "Turunkan Layer", hint: "Ctrl+[", action: "layer-down" },
    { label: "Layer Teratas", hint: "Ctrl+Shift+]", action: "layer-top" },
    { label: "Layer Terbawah", hint: "Ctrl+Shift+[", action: "layer-bottom" },
    { label: "Gabungkan ke Bawah", hint: "Ctrl+E", action: "merge-down" },
    { label: "Gabungkan Semua", hint: "Ctrl+Shift+E", action: "merge-all" },
    { label: "Flatten Image", hint: "", action: "flatten" },
    { label: "Layer Opacity", hint: "", action: "layer-opacity" },
    { label: "Blend Mode", hint: "", action: "blend-mode" },
    { label: "Add Layer Mask", hint: "", action: "add-mask" },
    { label: "Clipping Mask", hint: "Ctrl+Alt+G", action: "clip-mask" },
    { label: "Lock Layer", hint: "", action: "lock-layer" },
    { label: "Free Transform", hint: "Ctrl+T", action: "free-transform" },
    { label: "Guides", hint: "", action: "guides" },
  ],
  Select: [
    { label: "Semua", hint: "Ctrl+A", action: "sel-all" },
    { label: "Batalkan Pilihan", hint: "Ctrl+D", action: "sel-none" },
    { label: "Pilih Ulang", hint: "Ctrl+Shift+D", action: "sel-reselect" },
    { label: "Inverse", hint: "Ctrl+Shift+I", action: "sel-inverse" },
    { label: "Rectangular Marquee", hint: "M", action: "sel-rect" },
    { label: "Lasso", hint: "L", action: "sel-lasso" },
    { label: "Magic Wand", hint: "W", action: "wand" },
    { label: "Feather", hint: "Shift+F6", action: "sel-feather" },
    { label: "Select and Mask", hint: "", action: "select-mask" },
    { label: "Color Range", hint: "", action: "color-range" },
    { label: "Subject", hint: "", action: "select-subject" },
    { label: "Crop", hint: "C", action: "crop" },
  ],
  Filter: [
    { label: "Gaussian Blur", hint: "", action: "f-blur" },
    { label: "Box Blur", hint: "", action: "f-native-box" },
    { label: "Sharpen", hint: "", action: "f-native-sharpen" },
    { label: "Unsharp Mask", hint: "", action: "f-native-unsharp" },
    { label: "Emboss", hint: "", action: "f-native-emboss" },
    { label: "Motion Blur", hint: "", action: "f-motion" },
    { label: "Box Blur", hint: "", action: "f-box" },
    { label: "Sharpen", hint: "", action: "f-sharpen" },
    { label: "Unsharp Mask", hint: "", action: "f-unsharp" },
    { label: "High Pass", hint: "", action: "f-highpass" },
    { label: "Reduce Noise", hint: "", action: "f-denoise" },
    { label: "Add Noise", hint: "", action: "f-noise" },
    { label: "Film Grain", hint: "", action: "f-grain" },
    { label: "Pixelate", hint: "", action: "f-pixelate" },
    { label: "Halftone", hint: "", action: "f-halftone" },
    { label: "Emboss", hint: "", action: "f-emboss" },
    { label: "Find Edges", hint: "", action: "f-edges" },
    { label: "Oil Paint Lite", hint: "", action: "f-oil" },
    { label: "Tilt Shift", hint: "", action: "f-tilt" },
    { label: "Vignette", hint: "", action: "f-vignette" },
    { label: "Chromatic Aberration", hint: "", action: "f-chroma" },
    { label: "Filter Gallery", hint: "", action: "filter-gallery" },
  ],
  Adjust: [
    { label: "Grayscale", hint: "", action: "a-native-gray" },
    { label: "Invert", hint: "", action: "a-native-invert" },
    { label: "Contrast", hint: "", action: "a-native-contrast" },
    { label: "Brightness/Contrast", hint: "", action: "a-bc" },
    { label: "Levels", hint: "Ctrl+L", action: "a-levels" },
    { label: "Curves", hint: "Ctrl+M", action: "a-curves" },
    { label: "Exposure", hint: "", action: "a-exposure" },
    { label: "Hue/Saturation", hint: "Ctrl+U", action: "a-hsl" },
    { label: "Vibrance", hint: "", action: "a-vibrance" },
    { label: "Color Balance", hint: "Ctrl+B", action: "a-balance" },
    { label: "Black & White", hint: "Ctrl+Shift+Alt+B", action: "a-bw" },
    { label: "Photo Filter", hint: "", action: "a-photo" },
    { label: "Channel Mixer", hint: "", action: "a-mixer" },
    { label: "Gradient Map", hint: "", action: "a-gradmap" },
    { label: "Color Lookup", hint: "", action: "a-lut" },
    { label: "Selective Color", hint: "", action: "a-selective" },
    { label: "Shadows/Highlights", hint: "", action: "a-shhi" },
    { label: "Invert", hint: "Ctrl+I", action: "a-invert" },
    { label: "Posterize", hint: "", action: "a-posterize" },
    { label: "Threshold", hint: "", action: "a-threshold" },
  ],
  View: [
    { label: "Fit Zoom", hint: "", action: "fit" },
    { label: "Zoom In", hint: "Ctrl++", action: "zoom-in" },
    { label: "Zoom Out", hint: "Ctrl+-", action: "zoom-out" },
    { label: "Zoom 100%", hint: "Ctrl+1", action: "zoom100" },
    { label: "Zoom 200%", hint: "Ctrl+2", action: "zoom200" },
    { label: "Zoom 50%", hint: "Ctrl+0", action: "zoom50" },
    { label: "Actual Pixels", hint: "", action: "zoom100" },
    { label: "Rulers", hint: "Ctrl+R", action: "rulers" },
    { label: "Guides", hint: "Ctrl+;", action: "guides" },
    { label: "Grid", hint: "'", action: "grid" },
    { label: "Snap", hint: "", action: "snap" },
    { label: "Workspace Retouch", hint: "", action: "ws-retouch" },
    { label: "Workspace Photo", hint: "", action: "ws-photo" },
    { label: "Workspace Design", hint: "", action: "ws-design" },
    { label: "Workspace Minimal", hint: "", action: "ws-minimal" },
    { label: "Node Graph", hint: "", action: "nodegraph" },
    { label: "Tampilkan Onboarding", hint: "", action: "onboarding" },
  ],
  Help: [
    { label: "Shortcut dan Tips", hint: "Ctrl+K", action: "palette" },
    { label: "Tips Boot", hint: "", action: "tips" },
    { label: "Tentang AVERO", hint: "", action: "about" },
  ],
};
